import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const main=fs.readFileSync(new URL('../src/main.jsx',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../src/style.css',import.meta.url),'utf8');
const pkg=JSON.parse(fs.readFileSync(new URL('../package.json',import.meta.url),'utf8'));
test('Beta.13 exposes separate email and share golfer invites',()=>{assert.match(main,/EMAIL GGC INVITE/);assert.match(main,/SHARE INVITE LINK/)});
test('Beta.13 email invite uses corrected authenticated Edge Function and no client supplied URL',()=>{assert.match(main,/functions\.invoke\('send-ggc-invite',\{body:\{playerId:p\.id\}\}\)/);assert.doesNotMatch(main,/send-gcc-invite/)});
test('Beta.13 temporary golfers have no claim token until invited',()=>assert.match(main,/claimToken:null/));
test('Beta.13 share token uses Web Crypto and records sent only after share succeeds',()=>{assert.match(main,/crypto\.randomUUID/);assert.match(main,/await markSharedInviteSent\(p,invite\.token\)/)});
test('Beta.13 mobile competition group header uses name plus count only',()=>{assert.match(main,/groupCompName/);assert.match(main,/groupCompCount/);assert.doesNotMatch(main,/\{active\.length\} live \/ upcoming/)});
test('Beta.13 scheduled go-live text has spacing',()=>assert.match(css,/\.goLiveAt\{display:inline-block;margin-left:14px/));
test('Beta.13 build marker',()=>{assert.equal(pkg.version,'3.9.6-beta.13');assert.match(main,/Build 3\.9\.6 Beta\.13/)});
