import React,{useMemo,useState}from'react';
import{ArrowLeft,CheckCircle2,Trophy}from'lucide-react';
import{courseHandicap,playingHandicap,holeStrokes}from'./scoring.js';
import{GROUP_FORMAT_RULES,groupScore,groupLeaderboard,scrambleTeamHandicap}from'./groupScoring.js';

const fmt=v=>{const n=+v||0;return n<0?`+${Math.abs(n).toFixed(1)}`:n.toFixed(1)};
const id=()=>crypto.randomUUID?.()||Date.now()+''+Math.random();
export default function GroupScoreScreen({c,state,setState,me,back}){
 const course=state.courses.find(x=>x.id===c.course),tee=course?.tees?.find(t=>t.name===c.tee),hs=tee?.holes||[],par=hs.reduce((n,h)=>n+(+h.par||0),0)||72,rule=GROUP_FORMAT_RULES[c.format];
 const saved=(c.roundGroups||[]).find(g=>(g.playerIds||[]).includes(me.id));const[ids,setIds]=useState(saved?.playerIds||[me.id]);const[setup,setSetup]=useState(!saved);const[board,setBoard]=useState(false);
 const current=state.comps.find(x=>x.id===c.id)||c;const group=(current.roundGroups||[]).find(g=>g.id===saved?.id)||(current.roundGroups||[]).find(g=>(g.playerIds||[]).includes(me.id));const teamMode=rule?.mode==='team-gross';
 const candidates=state.players.filter(p=>[...new Set([...(state.societies.find(s=>s.id===c.societyId)?.members||[]),...(c.entries||[]),me.id])].includes(p.id));
 const selected=ids.map(x=>state.players.find(p=>p.id===x)).filter(Boolean);const result=group?groupScore(group,current,state):null;
 function setSlot(i,v){setIds(a=>{const n=[...a];n[i]=v;return n.filter(Boolean).filter((x,j,z)=>z.indexOf(x)===j).slice(0,4)})}
 function start(){const playerIds=[...new Set(ids)].filter(Boolean);if(playerIds.length<2)return alert('Group formats need at least two golfers.');const now=new Date().toISOString(),gid=saved?.id||id();let cards=[...state.cards];if(!teamMode)for(const pid of playerIds)if(!cards.some(x=>x.compId===c.id&&x.playerId===pid)){const p=state.players.find(x=>x.id===pid),ph=playingHandicap(p?.hi??0,tee,par,c.handicapAllowance??95);cards.push({id:id(),societyId:c.societyId,compId:c.id,playerId:pid,gross:Array(hs.length).fill(''),courseId:c.course,tee:c.tee,handicapIndexUsed:p?.hi??0,courseHandicap:courseHandicap(p?.hi??0,tee,par),playingHandicap:ph,submitted:false,updatedAt:now,lastEditedBy:me.id})}
 const newGroup={id:gid,playerIds,startedAt:saved?.startedAt||now,startedBy:me.id,teamGross:saved?.teamGross||Array(hs.length).fill(''),teamPlayingHandicap:saved?.teamPlayingHandicap};
 const comps=state.comps.map(q=>q.id===c.id?{...q,entries:[...new Set([...(q.entries||[]),...playerIds])],roundGroups:[...(q.roundGroups||[]).filter(g=>g.id!==gid&&!(g.playerIds||[]).some(x=>playerIds.includes(x))),newGroup]}:q);setState({...state,cards,comps});setSetup(false)}
 function changePlayer(pid,i,v){setState(prev=>({...prev,cards:prev.cards.map(card=>card.compId===c.id&&card.playerId===pid?{...card,gross:(card.gross||[]).map((x,j)=>j===i?v:x),updatedAt:new Date().toISOString(),lastEditedBy:me.id}:card)}))}
 function changeTeam(i,v){setState(prev=>({...prev,comps:prev.comps.map(q=>q.id!==c.id?q:{...q,roundGroups:(q.roundGroups||[]).map(g=>g.id!==group.id?g:{...g,teamGross:(g.teamGross||Array(hs.length).fill('')).map((x,j)=>j===i?v:x)})})}))}
 function submit(){const now=new Date().toISOString();setState(prev=>({...prev,cards:prev.cards.map(card=>card.compId===c.id&&ids.includes(card.playerId)?{...card,submitted:true,submittedAt:card.submittedAt||now}:card),comps:prev.comps.map(q=>q.id===c.id?{...q,roundGroups:(q.roundGroups||[]).map(g=>g.id===group?.id?{...g,submitted:true,submittedAt:g.submittedAt||now}:g)}:q)}));back()}
 if(setup)return <div className="app score groupScoreV2"><header><button className="icon" onClick={back}><ArrowLeft/></button><div><b>{c.name}</b><small>Beta.14 · New Group Scorecard</small></div></header><main><div className="card"><h3>GROUP SCORECARD</h3><p className="muted">This is the separate Group scoring system. Choose 2–4 golfers.</p>{[0,1,2,3].map(i=><label key={i}>Golfer {i+1}<select value={ids[i]||''} onChange={e=>setSlot(i,e.target.value)}><option value="">No golfer</option>{candidates.map(p=><option key={p.id} value={p.id}>{p.name} · HI {fmt(p.hi)}</option>)}</select></label>)}<button className="primary" onClick={start}>START GROUP SCORECARD</button></div></main></div>;
 const leaders=board?groupLeaderboard(current,state):[];
 return <div className="app score groupScoreV2"><header><button className="icon" onClick={back}><ArrowLeft/></button><div><b>{c.name}</b><small>{rule.name} · Beta.14 Group Engine</small></div></header><main><div className="groupFormatBanner"><b>{rule.name.toUpperCase()}</b><span>{teamMode?'ONE TEAM GROSS SCORE PER HOLE':c.format==='cha-cha-cha'?'1 / 2 / 3 SCORES COUNT':c.format==='irish-fourball'?'1 / 2 / 3 / 4 SCORES COUNT':c.format==='yellow-ball'?'YELLOW BALL + BEST OTHER SCORE':`BEST ${c.groupScoresCount??rule.count??2} SCORES COUNT`}</span></div><button className="secondary" onClick={()=>setBoard(x=>!x)}><Trophy/> {board?'HIDE':'VIEW'} GROUP LEADERBOARD</button>{board&&<div className="card"><h3>GROUP LEADERBOARD</h3>{leaders.map((r,i)=><div className="leaderrow" key={r.groupId}><strong>{i+1}</strong><span><b>{r.name}</b><small>{r.complete} holes</small></span><em>{r.lowerWins?`${r.rankValue} net`:`${r.points} pts`}</em></div>)}</div>}
 <div className="groupCardWrap"><div className="groupV2Grid"><div className="gvHead">HOLE</div><div className="gvHead">{teamMode?'TEAM':selected.map(p=>p.name.split(' ')[0]).join(' · ')}</div><div className="gvHead">COUNTING</div>{hs.map((h,i)=>{if(teamMode){const v=group?.teamGross?.[i]??'';return <React.Fragment key={i}><div className="holeMeta"><b>{h.n}</b><small>P{h.par} · SI {h.si}</small></div><div className="groupTeamInput"><button onClick={()=>changeTeam(i,Math.max(1,(+v||h.par)-1))}>−</button><input inputMode="numeric" value={v} placeholder={h.par} onChange={e=>changeTeam(i,e.target.value)}/><button onClick={()=>changeTeam(i,(+v||h.par)+1)}>+</button></div><div className="groupCounted">{v?`Gross ${v}`:''}</div></React.Fragment>}
 const detail=result?.holes?.[i];return <React.Fragment key={i}><div className="holeMeta"><b>{h.n}</b><small>P{h.par} · SI {h.si}</small></div><div className="groupPlayersHole">{selected.map(p=>{const card=state.cards.find(x=>x.compId===c.id&&x.playerId===p.id),v=card?.gross?.[i]??'',ph=card?.playingHandicap??0,shots=holeStrokes(ph,h.si),pts=v?Math.max(0,2+(h.par+shots-(+v||0))):null,counted=detail?.counted?.includes(p.id),yellow=detail?.yellowBallId===p.id;return <div className={`groupPlayerLine ${counted?'counted':''} ${yellow?'yellowBall':''}`} key={p.id}><b>{p.name.split(' ')[0]}{yellow?' 🟡':''}</b><button onClick={()=>changePlayer(p.id,i,Math.max(1,(+v||h.par)-1))}>−</button><input inputMode="numeric" value={v} placeholder={h.par} onChange={e=>changePlayer(p.id,i,e.target.value)}/><button onClick={()=>changePlayer(p.id,i,(+v||h.par)+1)}>+</button><span>{v?`${pts} pts`:''}</span></div>})}</div><div className="groupCounted">{detail?.points!=null?`${detail.points} pts`:''}</div></React.Fragment>})}</div></div>
 {teamMode&&<div className="card groupStatus"><b>TEAM HANDICAP</b><span>{Number.isFinite(+group?.teamPlayingHandicap)?group.teamPlayingHandicap.toFixed(1):scrambleTeamHandicap(ids,current,state).toFixed(1)} raw · {result?.teamHandicap??0} playing</span><small>Default scramble allowance is calculated low-to-high; a competition-specific team handicap can override it.</small></div>}
 <div className="card groupStatus"><b>TEAM TOTAL</b><span>{result?(result.lowerWins?`${result.net} nett from ${result.gross} gross`:`${result.points} points`):'No scores yet'}</span><small>{selected.map(p=>p.name).join(' · ')}</small></div><button className="primary" onClick={submit}><CheckCircle2/> SUBMIT GROUP ROUND</button></main></div>
}
