import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{Plus,Users,Flag,Wallet,Settings,ChevronRight,UserRound,Save,X,Share2,Copy,LogIn,Building2,Trophy,ArrowLeft,CheckCircle2,Trash2}from'lucide-react';
import'./style.css';
const SUPA_URL=import.meta.env.VITE_SUPABASE_URL||'';const SUPA_KEY=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||import.meta.env.VITE_SUPABASE_ANON_KEY||'';const CLOUD=!!(SUPA_URL&&SUPA_KEY);const K='ggc-build2';
const formats=[['stableford','Individual Stableford','Play your own ball. Highest Stableford points wins.'],['stroke','Stroke Play / Medal','Hole out every hole. Lowest net total wins.'],['4bbb','4 Ball Better Ball','Pairs. Better Stableford score counts on each hole.'],['waltz','Waltz','Team Stableford. 1, then 2, then 3 scores count, repeating.'],['best2','Best 2 from 4','Four-player team. Best two Stableford scores count each hole.'],['scramble','Texas Scramble','Choose the best shot and play on as a team.']];
const harlWhite=[[347,4,6],[166,3,8],[517,5,12],[397,4,2],[135,3,18],[535,5,10],[429,4,4],[367,4,16],[332,4,14],[381,4,7],[521,5,11],[596,5,1],[152,3,17],[410,4,5],[452,4,3],[166,3,9],[327,4,13],[285,4,15]];
const harlYellow=[[336,4,6],[160,3,8],[504,5,12],[388,4,2],[127,3,18],[527,5,10],[410,4,4],[357,4,16],[311,4,14],[374,4,7],[515,5,11],[577,5,1],[143,3,17],[401,4,5],[443,4,3],[127,3,9],[317,4,13],[276,4,15]];
const harlRed=[[324,4,4],[145,3,11],[452,5,5],[357,4,3],[119,3,18],[454,5,8],[365,4,7],[294,4,15],[296,4,10],[367,4,2],[458,5,6],[513,5,1],[131,3,17],[395,5,13],[436,5,12],[102,3,9],[280,4,14],[122,3,16]];
const holes=a=>a.map((x,i)=>({n:i+1,yards:x[0],par:x[1],si:x[2]}));
const defaultSoc={id:'default-society',name:'My Golf Society',code:'GGC-2026',members:[],createdAt:new Date().toISOString()};
const seed={version:2,players:[],societies:[defaultSoc],currentSocietyId:'default-society',courses:[{id:'harlestone',name:'Northampton Golf Club (Harlestone)',tees:[{id:'h-white',name:'White',rating:71.4,slope:133,holes:holes(harlWhite)},{id:'h-yellow',name:'Yellow',rating:70.4,slope:127,holes:holes(harlYellow)},{id:'h-red',name:'Red',rating:72.7,slope:132,holes:holes(harlRed)}]},{id:'staverton',name:'Staverton Park Golf Club',tees:[]},{id:'cold-ashby',name:'Cold Ashby Golf Centre',tees:[]},{id:'brampton',name:'Brampton Heath Golf Centre',tees:[]},{id:'sharpley',name:'Sharpley Golf',tees:[]},{id:'ramside',name:'Ramside Hall Golf Club',tees:[]}],comps:[],cards:[],oom:{},settings:{adminPin:'2026'}};
const clone=x=>JSON.parse(JSON.stringify(x));const uid=()=>crypto.randomUUID?.()||Date.now()+''+Math.random();const code=()=>`GGC-${Math.random().toString(36).slice(2,6).toUpperCase()}`;
function migrate(x){
 if(!x)return clone(seed);
 let y=x.version>=2?{...x}:{...seed,...x,version:2,societies:[defaultSoc],currentSocietyId:'default-society',comps:(x.comps||[]).map(c=>({...c,societyId:'default-society'})),cards:(x.cards||[]).map(c=>({...c,societyId:'default-society'}))};
 // Built-in courses are merged on every load so existing users receive newly added courses too.
 const builtins=clone(seed.courses); const existing=y.courses||[];
 for(const b of builtins){const i=existing.findIndex(c=>c.id===b.id||c.name===b.name);if(i<0)existing.push(b);else if(b.id==='harlestone'&&(!existing[i].tees||existing[i].tees.length===0))existing[i]=b;}
 return {...y,version:2,courses:existing,cards:y.cards||[],audit:y.audit||[]};
}
function App(){const[state,setState]=useState(()=>{try{return migrate(JSON.parse(localStorage.getItem(K))||JSON.parse(localStorage.getItem('ggc-build1')))}catch{return clone(seed)}});const[tab,setTab]=useState('home');const[cloud,setCloud]=useState(CLOUD?'Connecting…':'Local only');const[modal,setModal]=useState(null);const[me,setMe]=useState(()=>localStorage.getItem('ggc-me')||'');const[activeComp,setActiveComp]=useState(null);const[socId,setSocId]=useState(()=>localStorage.getItem('ggc-society')||'default-society');
useEffect(()=>{localStorage.setItem(K,JSON.stringify(state));if(CLOUD){const t=setTimeout(()=>saveCloud(state,setCloud),600);return()=>clearTimeout(t)}},[state]);useEffect(()=>{if(CLOUD)loadCloud().then(x=>x&&setState(migrate(x))).catch(()=>setCloud('Cloud unavailable'))},[]);
const currentMe=state.players.find(p=>p.id===me);const society=state.societies.find(s=>s.id===socId)||state.societies[0];const comps=state.comps.filter(c=>c.societyId===society?.id);const live=comps.filter(c=>new Date(c.ends)>=new Date()&&new Date(c.starts)<=new Date());
function addPlayer(p){const x={...p,id:uid()};setState(s=>({...s,players:[...s.players,x],societies:s.societies.map(q=>q.id===society?.id?{...q,members:[...new Set([...(q.members||[]),x.id])]}:q)}));setMe(x.id);localStorage.setItem('ggc-me',x.id);setModal(null)}
function enter(c){if(!currentMe){setModal('player');return}setActiveComp(c.id);setTab('score')}
if(tab==='score'){const c=state.comps.find(x=>x.id===activeComp);return <ScoreScreen c={c} state={state} setState={setState} me={currentMe} back={()=>setTab('home')}/>}
return <div className="app"><header><div className="brand"><div className="wordmark">GOLF <em>GAINZ</em><small>COMPS</small></div><span>Build 2.1 · {cloud}</span></div><button className="icon" onClick={()=>setTab('admin')}><Settings/></button></header><main>
{tab==='home'&&<><section className="hero"><p>GOLF GAINZ COMPS</p><h1>Golf competitions.<br/><em>Made simple.</em></h1><button onClick={()=>setModal('comp')}><Plus/> CREATE A COMP</button></section><SocietyBar society={society} setModal={setModal}/>{!currentMe?<div className="callout" onClick={()=>setModal('player')}><UserRound/><div><b>Set up your player</b><span>Add your name + Handicap Index once.</span></div><ChevronRight/></div>:<div className="me"><span>PLAYING AS</span><b>{currentMe.name} · HI {currentMe.hi}</b></div>}<SectionTitle a="LIVE COMPS" b={society?.name}/>{live.length?live.map(c=><CompCard key={c.id} c={c} state={state} enter={()=>enter(c)}/>):<Empty text="No live competitions in this society."/>}</>}
{tab==='comps'&&<><Title t="Competitions"/><button className="primary" onClick={()=>setModal('comp')}><Plus/>NEW COMPETITION</button>{comps.map(c=><CompCard key={c.id} c={c} state={state} enter={()=>enter(c)}/>)}</>}
{tab==='oom'&&<><Title t="Order of Merit"/><p className="muted">{society?.name} · field-size points. Team points are divided equally between team members.</p><Empty text="No OOM points awarded yet."/></>}
{tab==='me'&&<><Title t="My Golf"/>{currentMe?<div className="card"><h3>{currentMe.name}</h3><div className="big">HI {currentMe.hi}</div><button onClick={()=>{setMe('');localStorage.removeItem('ggc-me')}}>Change player</button></div>:<button className="primary" onClick={()=>setModal('player')}>SET UP MY PLAYER</button>}<h2>MY SOCIETIES</h2>{state.societies.filter(s=>(s.members||[]).includes(me)||s.id===society?.id).map(s=><button className="societyRow" key={s.id} onClick={()=>{setSocId(s.id);localStorage.setItem('ggc-society',s.id)}}><span><b>{s.name}</b><small>{s.code}</small></span>{s.id===society?.id&&<CheckCircle2/>}</button>)}<button className="secondary" onClick={()=>setModal('society')}><Plus/> CREATE / JOIN SOCIETY</button></>}
{tab==='admin'&&<Admin state={state} setState={setState} society={society}/>}</main><nav>{[['home','⌂','Home'],['comps','⚑','Comps'],['oom','★','OOM'],['me','●','Me']].map(x=><button className={tab===x[0]?'on':''} onClick={()=>setTab(x[0])} key={x[0]}><i>{x[1]}</i>{x[2]}</button>)}</nav>
{modal==='player'&&<PlayerModal close={()=>setModal(null)} add={addPlayer}/>} {modal==='comp'&&<CompModal state={state} setState={setState} society={society} close={()=>setModal(null)}/>} {modal==='society'&&<SocietyModal state={state} setState={setState} me={currentMe} setSocId={setSocId} close={()=>setModal(null)}/>} {modal==='share'&&<ShareModal society={society} close={()=>setModal(null)}/>}</div>}
function SocietyBar({society,setModal}){return <div className="societybar"><Building2/><div><small>CURRENT SOCIETY</small><b>{society?.name}</b></div><button onClick={()=>setModal('share')}><Share2/></button><button onClick={()=>setModal('society')}><ChevronRight/></button></div>}
function SectionTitle({a,b}){return <div className="sectiontitle"><h2>{a}</h2><span>{b}</span></div>}function Title({t}){return <div className="title"><h1>{t}</h1></div>}function Empty({text}){return <div className="empty">{text}</div>}
function CompCard({c,state,enter}){const f=formats.find(x=>x[0]===c.format);const course=state.courses.find(x=>x.id===c.course);return <div className="comp card"><div className="pill">LIVE</div><h3>{c.name}</h3><p>{f?.[1]} · {course?.name||'Course'} · {c.tee||''}</p><div className="meta"><span><Users/> {c.entries?.length||0}</span><span><Wallet/> £{c.fee||0}</span><span><Flag/> {c.days} day{c.days>1?'s':''}</span></div><button className="primary" onClick={enter}>ENTER / CONTINUE ROUND <ChevronRight/></button></div>}
function PlayerModal({close,add}){const[n,setN]=useState('');const[h,setH]=useState('');return <Modal close={close} title="Set up player"><label>Name<input value={n} onChange={e=>setN(e.target.value)} placeholder="Your name"/></label><label>Handicap Index<input type="number" step="0.1" value={h} onChange={e=>setH(e.target.value)} placeholder="8.5"/></label><button className="primary" disabled={!n||h===''} onClick={()=>add({name:n.trim(),hi:+h})}><Save/>SAVE & REMEMBER ME</button></Modal>}
function CompModal({state,setState,society,close}){const[name,setName]=useState('Weekend Comp');const[format,setFormat]=useState('stableford');const[course,setCourse]=useState(state.courses[0]?.id||'');const[tee,setTee]=useState(state.courses.find(x=>x.id===course)?.tees[0]?.name||'');const[fee,setFee]=useState(3);const[days,setDays]=useState(1);const[separate,setSeparate]=useState(false);function create(){let s=new Date(),e=new Date();e.setDate(e.getDate()+days);e.setHours(23,59,59,999);setState(x=>({...x,comps:[...x.comps,{id:uid(),societyId:society.id,name,format,course,tee,fee:+fee,days:+days,separateDailyPots:separate,starts:s.toISOString(),ends:e.toISOString(),entries:[]}]}));close()}return <Modal close={close} title="Create competition"><label>Competition name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Format<select value={format} onChange={e=>setFormat(e.target.value)}>{formats.map(f=><option key={f[0]} value={f[0]}>{f[1]}</option>)}</select><small>{formats.find(f=>f[0]===format)?.[2]}</small></label><label>Course<select value={course} onChange={e=>{setCourse(e.target.value);setTee(state.courses.find(x=>x.id===e.target.value)?.tees[0]?.name||'')}}>{state.courses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Tees<select value={tee} onChange={e=>setTee(e.target.value)}><option value="">Choose / add in Admin</option>{state.courses.find(x=>x.id===course)?.tees.map(t=><option key={t.id}>{t.name}</option>)}</select></label><div className="grid"><label>£ per player<input type="number" value={fee} onChange={e=>setFee(e.target.value)}/></label><label>Duration<select value={days} onChange={e=>setDays(+e.target.value)}><option value="1">1 day</option><option value="2">2 days</option><option value="7">1 week</option></select></label></div><label className="check"><input type="checkbox" checked={separate} onChange={e=>setSeparate(e.target.checked)}/> Keep each day's money separate</label><button className="primary" onClick={create}><Trophy/>CREATE COMPETITION</button></Modal>}
function SocietyModal({state,setState,me,setSocId,close}){const[name,setName]=useState('');const[join,setJoin]=useState('');function create(){if(!name.trim())return;const s={id:uid(),name:name.trim(),code:code(),members:me?[me.id]:[],createdAt:new Date().toISOString()};setState(x=>({...x,societies:[...x.societies,s]}));setSocId(s.id);localStorage.setItem('ggc-society',s.id);close()}function doJoin(){const s=state.societies.find(x=>x.code.toUpperCase()===join.trim().toUpperCase());if(!s)return alert('Society code not found on this GGC database.');setState(x=>({...x,societies:x.societies.map(q=>q.id===s.id&&me?{...q,members:[...new Set([...(q.members||[]),me.id])]}:q)}));setSocId(s.id);localStorage.setItem('ggc-society',s.id);close()}return <Modal close={close} title="Societies"><h3>Create a society</h3><label>Society name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Back 9 Bandits"/></label><button className="primary" onClick={create}><Plus/>CREATE SOCIETY</button><div className="divider">OR</div><h3>Join a society</h3><label>Private join code<input value={join} onChange={e=>setJoin(e.target.value.toUpperCase())} placeholder="B9B-4827"/></label><button className="secondary" onClick={doJoin}><LogIn/> JOIN SOCIETY</button></Modal>}
function ShareModal({society,close}){const msg=`⛳ Join my golf society on GGC!\n${society.name}\nJoin code: ${society.code}\nOpen GGC → My Golf → Create / Join Society.`;async function share(){if(navigator.share)await navigator.share({title:`Join ${society.name}`,text:msg});else{await navigator.clipboard.writeText(msg);alert('Invite copied')}}return <Modal close={close} title="Invite golfers"><div className="invite"><small>SOCIETY</small><h2>{society.name}</h2><span>PRIVATE JOIN CODE</span><strong>{society.code}</strong></div><button className="primary" onClick={share}><Share2/>SHARE INVITE</button><button className="secondary" onClick={async()=>{await navigator.clipboard.writeText(msg);alert('Invite copied')}}><Copy/> COPY INVITE</button></Modal>}
function ScoreScreen({c,state,setState,me,back}){
 if(!c)return <div className="app"><main><Empty text="Competition not found."/></main></div>;
 const course=state.courses.find(x=>x.id===c.course);const tee=course?.tees.find(t=>t.name===c.tee);const hs=tee?.holes||[];
 const society=state.societies.find(s=>s.id===c.societyId);const memberIds=society?.members||[];
 const eligible=state.players.filter(p=>memberIds.includes(p.id)||p.id===me.id);
 const[playerId,setPlayerId]=useState(me.id);const player=state.players.find(p=>p.id===playerId)||me;
 const existing=state.cards.find(x=>x.compId===c.id&&x.playerId===player.id);
 const[gross,setGross]=useState(existing?.gross||Array(hs.length).fill(''));
 useEffect(()=>{const e=state.cards.find(x=>x.compId===c.id&&x.playerId===playerId);setGross(e?.gross||Array(hs.length).fill(''))},[playerId,c.id,hs.length]);
 const par=hs.reduce((a,h)=>a+h.par,0)||72;const ch=Math.round((player.hi+(tee?.rating-par))*(tee?.slope||113)/113);
 function strokes(si){return Math.floor(ch/18)+(si<=ch%18?1:0)}function pts(h,i){const g=+gross[i];if(!g)return 0;return Math.max(0,2+(h.par+strokes(h.si)-g))}
 const total=gross.reduce((a,g)=>a+(+g||0),0),points=hs.reduce((a,h,i)=>a+pts(h,i),0);
 function addGolfer(){const name=prompt('Golfer name');if(!name)return;const hi=prompt('Handicap Index');if(hi===null||hi===''||isNaN(+hi))return alert('Enter a valid Handicap Index.');const id=uid();const p={id,name:name.trim(),hi:+hi};setState(s=>({...s,players:[...s.players,p],societies:s.societies.map(q=>q.id===c.societyId?{...q,members:[...new Set([...(q.members||[]),id])]}:q)}));setPlayerId(id)}
 function save(submitted=false){const now=new Date().toISOString();const old=state.cards.find(x=>x.compId===c.id&&x.playerId===player.id);const card={id:old?.id||uid(),societyId:c.societyId,compId:c.id,playerId:player.id,gross,courseId:c.course,tee:c.tee,courseHandicap:ch,submitted,submittedAt:submitted?(old?.submittedAt||now):old?.submittedAt,updatedAt:now,lastEditedBy:me.id};
 const action=old?.submitted?'EDIT SUBMITTED CARD':submitted?'SUBMIT CARD':old?'EDIT CARD':'CREATE CARD';
 const audit={id:uid(),societyId:c.societyId,compId:c.id,cardId:card.id,playerId:player.id,playerName:player.name,editedById:me.id,editedByName:me.name,action,at:now,before:old?{gross:old.gross,submitted:old.submitted}:null,after:{gross:[...gross],submitted}};
 setState(s=>({...s,cards:[...s.cards.filter(x=>!(x.compId===c.id&&x.playerId===player.id)),card],audit:[...(s.audit||[]),audit],comps:s.comps.map(q=>q.id===c.id?{...q,entries:[...new Set([...(q.entries||[]),player.id])]}:q)}));
 if(submitted)alert(old?.submitted?'Submitted card updated — change recorded in audit trail.':'Card submitted. You can reopen it later; any changes will be recorded in the audit trail.');}
 const history=(state.audit||[]).filter(a=>a.compId===c.id&&a.playerId===player.id).slice().reverse();
 return <div className="app score"><header><button className="icon" onClick={back}><ArrowLeft/></button><div><b>{c.name}</b><small>{course?.name} · {c.tee}</small></div><span className="scoretotal">{c.format==='stroke'?total:points}</span></header><main>
 <div className="scorefor"><label>SCORING FOR<select value={playerId} onChange={e=>setPlayerId(e.target.value)}>{eligible.map(p=><option key={p.id} value={p.id}>{p.name} · HI {p.hi}</option>)}</select></label><button className="secondary mini" onClick={addGolfer}><Plus/> ADD GOLFER</button></div>
 {existing?.submitted&&<div className="submittednote"><CheckCircle2/><div><b>Submitted card</b><span>You can edit it. Every change is recorded below.</span></div></div>}
 <div className="scoreintro"><span>{player.name}</span><b>HI {player.hi} · CH {ch}</b></div>{hs.length?hs.map((h,i)=><div className="hole" key={h.n}><div><strong>{h.n}</strong><span>PAR {h.par} · SI {h.si}<br/>{h.yards?`${h.yards} YDS · `:''}{strokes(h.si)} SHOT{strokes(h.si)!==1?'S':''}</span></div><div className="stepper"><button onClick={()=>setGross(a=>a.map((v,j)=>j===i?Math.max(1,(+v||h.par)-1):v))}>−</button><input inputMode="numeric" value={gross[i]} placeholder={h.par} onChange={e=>setGross(a=>a.map((v,j)=>j===i?e.target.value:v))}/><button onClick={()=>setGross(a=>a.map((v,j)=>j===i?(+v||h.par)+1:v))}>+</button></div><b className="pts">{gross[i]?`${pts(h,i)} pts`:''}</b></div>):<Empty text="This tee has no hole data yet. Add it in Admin before scoring."/>}<div className="scoreactions"><button className="secondary" onClick={()=>save(false)}><Save/> SAVE CARD</button><button className="primary" disabled={!hs.length} onClick={()=>save(true)}><CheckCircle2/> {existing?.submitted?'UPDATE SUBMITTED CARD':'SUBMIT CARD'}</button></div>
 {history.length>0&&<div className="audit card"><h3>AUDIT TRAIL</h3>{history.map(a=><div className="auditrow" key={a.id}><b>{a.action}</b><span>{new Date(a.at).toLocaleString()} · by {a.editedByName}</span></div>)}</div>}
 </main></div>}
function Admin({state,setState,society}){const[ok,setOk]=useState(false);const[pin,setPin]=useState('');if(!ok)return <><Title t="Admin"/><div className="card"><p>Admin is kept out of the normal golfer flow.</p><label>PIN<input type="password" value={pin} onChange={e=>setPin(e.target.value)}/></label><button className="primary" onClick={()=>setOk(pin===state.settings.adminPin)}>UNLOCK</button></div></>;return <><Title t="Admin"/><h2>{society?.name}</h2><p className="muted">Society-scoped competitions, OOM and members are isolated from other societies.</p><h2>COURSES</h2>{state.courses.map(c=><div className="course card" key={c.id}><b>{c.name}</b><span>{c.tees.length} saved tee{c.tees.length!==1?'s':''}</span></div>)}<button className="primary" onClick={()=>{const name=prompt('Course name');if(name)setState(s=>({...s,courses:[...s.courses,{id:uid(),name,tees:[]}]}))}}><Plus/>ADD COURSE</button><h2>DATA</h2><button className="danger" onClick={()=>{if(confirm('Clear all GGC Build 2 data?')&&confirm('Really clear everything?'))setState(clone(seed))}}><Trash2/>FACTORY RESET</button></>}
function Modal({close,title,children}){return <div className="shade"><div className="modal"><div className="modalhead"><h2>{title}</h2><button className="icon" onClick={close}><X/></button></div>{children}</div></div>}
async function loadCloud(){const r=await fetch(`${SUPA_URL}/rest/v1/ggc_state?id=eq.main&select=payload`,{headers:{apikey:SUPA_KEY}});if(!r.ok)throw Error(await r.text());const a=await r.json();return a[0]?.payload}async function saveCloud(s,set){set('Saving…');try{const r=await fetch(`${SUPA_URL}/rest/v1/ggc_state`,{method:'POST',headers:{apikey:SUPA_KEY,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates'},body:JSON.stringify({id:'main',payload:s,updated_at:new Date().toISOString()})});if(!r.ok)throw Error(await r.text());set('Cloud saved')}catch{set('Cloud save failed')}}
createRoot(document.getElementById('root')).render(<App/>);
