export const FORMAT_RULES={
 stableford:{verified:true,lowerWins:false,description:'Individual Stableford. Handicap strokes are applied hole by hole and the highest points total wins.',entry:'Enter gross strokes for every hole. GGC shows Stableford points.',result:'Highest Stableford points wins.'},
 stroke:{verified:true,lowerWins:true,description:'Individual nett Medal / Stroke Play.',entry:'Enter gross strokes. Handicap strokes are applied to produce nett hole and round scores.',result:'Lowest nett total wins.'},
 'gross-stroke':{verified:true,lowerWins:true,description:'Scratch Medal with no handicap deduction.',entry:'Enter gross strokes for every hole.',result:'Lowest gross total wins.'},
 'par-bogey':{verified:true,lowerWins:false,description:'Match play against the course using nett par on each hole.',entry:'Enter gross strokes. Each hole is shown as W, H or L after handicap strokes.',result:'Win +1, Half 0, Loss -1. Highest final +/- wins.'},
 'blind-pairs':{verified:true,lowerWins:false,description:'Everyone completes an individual Stableford card, then the field is paired in a one-time random draw.',entry:'Individual gross score entry with Stableford points. Draw becomes available only when all cards are complete.',result:'Pair Stableford totals are combined. Highest pair total wins.'},
 '4bbb':{verified:false},'aggregate-pairs':{verified:false},foursomes:{verified:false},greensomes:{verified:false},gruesomes:{verified:false},pinehurst:{verified:false},scramble:{verified:false},'scramble-standard':{verified:false},florida:{verified:false},'pairs-scramble':{verified:false},shamble:{verified:false},best1:{verified:false},best2:{verified:false},best3:{verified:false},waltz:{verified:false},'cha-cha-cha':{verified:false},'irish-fourball':{verified:false},bowmaker:{verified:false},alliance:{verified:false},'yellow-ball':{verified:false},sixes:{verified:false},skins:{verified:false},nassau:{verified:false},matchplay:{verified:false},'fourball-match':{verified:false},'foursomes-match':{verified:false},eclectic:{verified:false},flag:{verified:false},quota:{verified:false},'max-score':{verified:false},'modified-stableford':{verified:false}
};
export function courseHandicap(hi,tee,par){return Math.round((+hi||0)*(+tee?.slope||113)/113+((+tee?.rating||par)-par))}
export function holeStrokes(ch,si){const base=Math.trunc(ch/18),rem=Math.abs(ch%18);return ch>=0?base+(si<=rem?1:0):base-(si<=rem?1:0)}
export function scoreCard(card,c,state){const p=state.players.find(x=>x.id===card.playerId);const course=state.courses.find(x=>x.id===card.courseId||x.id===c.course);const tee=course?.tees.find(t=>t.name===(card.tee||c.tee));const hs=tee?.holes||[];const par=hs.reduce((a,h)=>a+h.par,0)||72;const ch=card.courseHandicap??courseHandicap(p?.hi,tee,par);const selected=c.holesMode==='front9'?[0,1,2,3,4,5,6,7,8]:c.holesMode==='back9'?[9,10,11,12,13,14,15,16,17]:hs.map((_,i)=>i);let gross=0,points=0,bogey=0,usedShots=0;const detail=hs.map((h,i)=>{const active=selected.includes(i),g=active?+(card.gross?.[i]||0):0,shots=holeStrokes(ch,h.si),net=g?g-shots:0,sp=g?Math.max(0,2+(h.par+shots-g)):0,b=g?(net<h.par?1:net===h.par?0:-1):0;if(g){gross+=g;points+=sp;bogey+=b;usedShots+=shots}return{gross:g,shots,net,points:sp,bogey:b,active}});const complete=selected.filter(i=>detail[i]?.gross>0).length;const net=gross-usedShots;let rankValue=points;if(c.format==='stroke')rankValue=net;if(c.format==='gross-stroke')rankValue=gross;if(c.format==='par-bogey')rankValue=bogey;return{player:p,points,gross,net,bogey,courseHandicap:ch,complete,holes:detail,rankValue}}
export function formatResult(r,format){if(format==='stroke')return `${r.net} net`;if(format==='gross-stroke')return `${r.gross} gross`;if(format==='par-bogey')return r.bogey>0?`+${r.bogey}`:`${r.bogey}`;return `${r.points} pts`}
export function validateFormatStart(format,count){if(format==='4bbb'&&count<4)return '4BBB needs at least four golfers (two pairs).';if(format==='blind-pairs'&&count<2)return 'Blind Pairs needs at least two golfers.';return null}
