export const FORMAT_RULES={
 stableford:{verified:true,category:'individual',defaultAllowance:95,lowerWins:false,description:'Individual Stableford. Handicap strokes are applied hole by hole and the highest points total wins.',entry:'Enter gross strokes for every hole. GGC calculates Stableford points.',result:'Highest Stableford points wins.'},
 stroke:{verified:true,category:'individual',defaultAllowance:95,lowerWins:true,description:'Individual nett Medal / Stroke Play.',entry:'Enter gross strokes. Playing Handicap is applied hole by hole.',result:'Lowest nett total wins.'},
 'gross-stroke':{verified:true,category:'individual',defaultAllowance:0,lowerWins:true,description:'Scratch Medal with no handicap adjustment.',entry:'Enter gross strokes for every hole.',result:'Lowest gross total wins.'},
 'par-bogey':{verified:true,category:'individual',defaultAllowance:95,lowerWins:false,description:'Play match play against the course using nett par on every hole.',entry:'Enter gross strokes. GGC marks each hole W, H or L.',result:'Win +1, Half 0, Loss -1. Highest final +/- wins.'},
 'max-score':{verified:true,category:'individual',defaultAllowance:95,lowerWins:true,description:'Stroke play with a maximum score on each hole.',entry:'Enter gross strokes. GGC applies the configured cap automatically.',result:'Lowest capped nett total wins.'},
 'modified-stableford':{verified:true,category:'individual',defaultAllowance:95,lowerWins:false,description:'Stableford-style scoring using the competition’s configurable points table.',entry:'Enter gross strokes. GGC converts each nett score relative to par into the configured points.',result:'Highest modified points total wins.'},
 flag:{verified:true,category:'individual',defaultAllowance:100,lowerWins:false,description:'Each golfer has a stroke budget based on course par plus Playing Handicap. The flag is placed where that allowance runs out.',entry:'Enter scores up to the point your allowance expires, then record the hole reached and shot position. If you finish 18, record strokes left.',result:'Furthest progress wins; golfers completing 18 rank by strokes remaining.'},
 eclectic:{verified:true,category:'individual',defaultAllowance:95,lowerWins:true,description:'Best score recorded on each hole across multiple rounds.',entry:'Choose the round being played and enter its gross scores. GGC keeps the best score for each hole.',result:'Lowest best-hole aggregate wins.'},
 waltz:{verified:true,category:'individual',defaultAllowance:95,lowerWins:false,description:'Individual Stableford with a repeating 1×, 2×, 3× multiplier.',entry:'Enter gross strokes. GGC applies 1× on hole 1, 2× on hole 2, 3× on hole 3 and repeats.',result:'Highest weighted Stableford total wins.'},
 'blind-pairs':{verified:true,category:'pairs',defaultAllowance:95,lowerWins:false,description:'Blind Pairs Stableford. Individual cards are combined after the draw.',entry:'Each golfer enters their own gross scores.',result:'Highest combined pair Stableford total wins.'},
 best1:{verified:true,category:'group',defaultAllowance:75,lowerWins:false,description:'Team Stableford for 3–4 golfers. The best one Stableford score on each hole counts.',entry:'Enter each golfer’s gross score on the shared group card.',result:'Highest team total wins.'},best2:{verified:true,category:'group',defaultAllowance:85,lowerWins:false,description:'Team Stableford for 3–4 golfers. The best two Stableford scores on each hole count.',entry:'Enter each golfer’s gross score on the shared group card.',result:'Highest team total wins.'},best3:{verified:true,category:'group',defaultAllowance:100,lowerWins:false,description:'Team Stableford for 3–4 golfers. The best three Stableford scores on each hole count.',entry:'Enter each golfer’s gross score on the shared group card.',result:'Highest team total wins.'},'cha-cha-cha':{verified:true,category:'group',defaultAllowance:85,lowerWins:false,description:'Team Stableford: best 1 score counts on hole 1, best 2 on hole 2, best 3 on hole 3, then repeat.',entry:'Enter every golfer’s gross score.',result:'Highest weighted team Stableford total wins.'},'irish-fourball':{verified:true,category:'group',defaultAllowance:85,lowerWins:false,description:'GGC Irish Fourball: best 1 score counts on holes 1–6, best 2 on 7–12, best 3 on 13–17 and all available scores on 18.',entry:'Enter every golfer’s gross score.',result:'Highest team Stableford total wins.'},bowmaker:{verified:true,category:'group',defaultAllowance:85,lowerWins:false,description:'Bowmaker team Stableford: best two Stableford scores on each hole count.',entry:'Enter every golfer’s gross score.',result:'Highest team total wins.'},alliance:{verified:true,category:'group',defaultAllowance:85,lowerWins:false,description:'Alliance team Stableford: best two Stableford scores on each hole count.',entry:'Enter every golfer’s gross score.',result:'Highest team total wins.'},'yellow-ball':{verified:true,category:'group',defaultAllowance:85,lowerWins:false,description:'Yellow Ball: the nominated ball rotates through the group; its Stableford score plus the best other score count on each hole.',entry:'Enter every golfer’s gross score. Yellow-ball duty rotates in the order shown on the scorecard.',result:'Highest team total wins.'},
 '4bbb':{verified:false},'4bbb-stableford':{verified:true,category:'pairs',defaultAllowance:85,lowerWins:false,description:'Four-Ball Stableford: both partners play their own ball; best Stableford score on each hole counts.',entry:'Each partner enters their own gross score.',result:'Highest Better-Ball Stableford total wins.'},'4bbb-stroke':{verified:true,category:'pairs',defaultAllowance:85,lowerWins:true,description:'Four-Ball stroke play: both partners play their own ball; lowest nett score on each hole counts.',entry:'Each partner enters their own gross score.',result:'Lowest Better-Ball nett total wins.'},'aggregate-stableford':{verified:true,category:'pairs',defaultAllowance:95,lowerWins:false,description:'Both partners play their own ball and both Stableford scores count.',entry:'Each partner enters their own gross score.',result:'Highest combined Stableford total wins.'},'aggregate-stroke':{verified:true,category:'pairs',defaultAllowance:95,lowerWins:true,description:'Both partners play their own ball and both nett scores count.',entry:'Each partner enters their own gross score.',result:'Lowest combined nett total wins.'},'4bbb-match':{verified:true,category:'pairs',defaultAllowance:90,lowerWins:false,description:'Four-Ball match play between two pairs.',entry:'All four golfers enter their own gross scores.',result:'Best nett result on each hole wins the hole; most holes up wins the match.'},'aggregate-pairs':{verified:false},foursomes:{verified:false},greensomes:{verified:false},gruesomes:{verified:false},pinehurst:{verified:false},scramble:{verified:false},'scramble-standard':{verified:false},florida:{verified:false},'pairs-scramble':{verified:false},shamble:{verified:false},sixes:{verified:false},skins:{verified:false},nassau:{verified:false},matchplay:{verified:false},'fourball-match':{verified:false},'foursomes-match':{verified:false},quota:{verified:false}
};
export function rawCourseHandicap(hi,tee,par){return (+hi||0)*(+tee?.slope||113)/113+((+tee?.rating||par)-par)}
export function whsRound(n){return n<0?-Math.round(Math.abs(n)):Math.round(n)}
export function playingHandicapFromRaw(raw,allowance=100){return whsRound(raw*(Math.max(0,Math.min(100,+allowance||0))/100))}
export function courseHandicap(hi,tee,par){return whsRound(rawCourseHandicap(hi,tee,par))}
export function playingHandicap(hi,tee,par,allowance=100){return playingHandicapFromRaw(rawCourseHandicap(hi,tee,par),allowance)}
export function holeStrokes(ch,si){const base=Math.trunc(ch/18),rem=Math.abs(ch%18);return ch>=0?base+(si<=rem?1:0):base-(rem>0&&si>18-rem?1:0)}
function selectedIndexes(c,hs){return c.holesMode==='front9'?[0,1,2,3,4,5,6,7,8]:c.holesMode==='back9'?[9,10,11,12,13,14,15,16,17]:hs.map((_,i)=>i)}
function modifiedPoints(net,par,table={}){const d=net-par;if(d<=-3)return +(table.albatross??8);if(d===-2)return +(table.eagle??5);if(d===-1)return +(table.birdie??2);if(d===0)return +(table.par??0);if(d===1)return +(table.bogey??-1);return +(table.double??-3)}
function effectiveGross(card,c,hs){if(c.format!=='eclectic')return card.gross||[];const rounds=Array.isArray(card.eclecticRounds)?card.eclecticRounds:[];return hs.map((_,i)=>{const vals=rounds.map(r=>+(r?.gross?.[i]||0)).filter(v=>v>0);return vals.length?Math.min(...vals):0})}
export function scoreCard(card,c,state){
 const p=state.players.find(x=>x.id===card.playerId);const course=state.courses.find(x=>x.id===card.courseId||x.id===c.course);const tee=course?.tees.find(t=>t.name===(card.tee||c.tee));const hs=tee?.holes||[];const par=hs.reduce((a,h)=>a+h.par,0)||72;
 const allowance=c.format==='gross-stroke'?0:(c.handicapAllowance??FORMAT_RULES[c.format]?.defaultAllowance??100);const ch=card.courseHandicap??courseHandicap(card.handicapIndexUsed??p?.hi,tee,par);const ph=card.playingHandicap??playingHandicap(card.handicapIndexUsed??p?.hi,tee,par,allowance);const selected=selectedIndexes(c,hs);const sourceGross=effectiveGross(card,c,hs);let gross=0,points=0,bogey=0,usedShots=0,cappedGross=0,modified=0,waltz=0;
 const detail=hs.map((h,i)=>{const active=selected.includes(i),g=active?+(sourceGross?.[i]||0):0,shots=holeStrokes(ph,h.si),rawNet=g?g-shots:0,sp=g?Math.max(0,2+(h.par+shots-g)):0,b=g?(rawNet<h.par?1:rawNet===h.par?0:-1):0;let capped=g;if(g&&c.format==='max-score'){if(c.maxScoreMode==='double-par')capped=Math.min(g,h.par*2);else if(c.maxScoreMode==='net-double-bogey')capped=Math.min(g,h.par+2+shots);else capped=Math.min(g,Math.max(1,+c.maxScore||8))}const net=g?capped-shots:0;const mp=g?modifiedPoints(rawNet,h.par,c.modifiedPoints):0;const mult=(i%3)+1;const wp=g?sp*mult:0;if(g){gross+=g;cappedGross+=capped;points+=sp;bogey+=b;usedShots+=shots;modified+=mp;waltz+=wp}return{gross:g,cappedGross:capped,shots,net,points:sp,bogey:b,modifiedPoints:mp,multiplier:mult,waltzPoints:wp,active}});
 const complete=selected.filter(i=>detail[i]?.gross>0).length;let net=(c.format==='max-score'?cappedGross:gross)-usedShots;if(c.format==='eclectic'&&c.eclecticScoring==='gross')net=gross;let rankValue=points;if(c.format==='stroke'||c.format==='max-score'||c.format==='eclectic')rankValue=net;if(c.format==='gross-stroke')rankValue=gross;if(c.format==='par-bogey')rankValue=bogey;if(c.format==='modified-stableford')rankValue=modified;if(c.format==='waltz')rankValue=waltz;if(c.format==='flag'){const fr=card.flagResult||{};rankValue=fr.completed18?100000+(+fr.strokesLeft||0):((+fr.hole||0)*100)-(+fr.shot||99)}return{player:p,points,gross,cappedGross,net,bogey,modified,waltz,courseHandicap:ch,playingHandicap:ph,complete,holes:detail,rankValue,flagResult:card.flagResult||null}
}
export function formatResult(r,format){if(format==='stroke'||format==='max-score')return `${r.net} net`;if(format==='gross-stroke')return `${r.gross} gross`;if(format==='par-bogey')return r.bogey>0?`+${r.bogey}`:`${r.bogey}`;if(format==='modified-stableford')return `${r.modified} pts`;if(format==='waltz')return `${r.waltz} pts`;if(format==='eclectic')return `${r.net} ${r.net===r.gross?'gross':'net'}`;if(format==='flag'){const f=r.flagResult;if(!f)return 'Flag result needed';return f.completed18?`18 finished · ${+f.strokesLeft||0} left`:`Hole ${f.hole} · shot ${f.shot}`}return `${r.points} pts`}
export function validateFormatStart(format,count){return null}
export function normaliseBlindPairIds(pair){return Array.isArray(pair)?pair:Array.isArray(pair?.ids)?pair.ids:[]}
export function oomPointsForField(n){if(n<5)return[];const first=n<=8?10:n<=12?12:n<=16?14:16;return Array.from({length:n},(_,i)=>Math.max(0,first-(i*2)))}

export function pairScore(pair,c,state){
 const ids=(pair?.ids||pair||[]).slice(0,2); const cards=ids.map(id=>state.cards.find(x=>x.compId===c.id&&x.playerId===id)).filter(Boolean); const rs=cards.map(card=>scoreCard(card,c,state));
 if(!rs.length)return {ids,complete:0,rankValue:c.format.includes('stroke')?99999:-99999,points:0,net:0,holes:[]};
 const n=Math.max(...rs.map(r=>r.holes.length)); let points=0,net=0; const holes=[];
 for(let i=0;i<n;i++){const hs=rs.map(r=>r.holes[i]).filter(h=>h?.gross>0); if(!hs.length){holes.push(null);continue}
   if(c.format==='4bbb-stableford'||c.format==='4bbb-match'){const v=Math.max(...hs.map(h=>h.points));points+=v;holes.push({value:v});}
   else if(c.format==='4bbb-stroke'){const v=Math.min(...hs.map(h=>h.net));net+=v;holes.push({value:v});}
   else if(c.format==='aggregate-stableford'||c.format==='blind-pairs'){const v=hs.reduce((a,h)=>a+h.points,0);points+=v;holes.push({value:v});}
   else if(c.format==='aggregate-stroke'){const v=hs.reduce((a,h)=>a+h.net,0);net+=v;holes.push({value:v});}
 }
 const complete=holes.filter(Boolean).length; const lower=c.format==='4bbb-stroke'||c.format==='aggregate-stroke'; return {ids,complete,points,net,holes,rankValue:lower?net:points};
}
export function groupTeamScore(group,c,state){
 const ids=(group?.playerIds||group?.ids||[]).filter(Boolean);const cards=ids.map(id=>state.cards.find(x=>x.compId===c.id&&x.playerId===id)).filter(Boolean);const rs=cards.map(card=>scoreCard(card,c,state));
 if(!rs.length)return {ids,complete:0,points:0,rankValue:-99999,holes:[]};
 const n=Math.max(...rs.map(r=>r.holes.length));let points=0;const holes=[];
 for(let i=0;i<n;i++){const vals=rs.map((r,idx)=>({id:ids[idx],points:r.holes[i]?.gross>0?r.holes[i].points:null}));const available=vals.filter(x=>x.points!==null);if(!available.length){holes.push(null);continue}
   let count=1,used=[];
   if(c.format==='best2'||c.format==='bowmaker'||c.format==='alliance')count=2;
   else if(c.format==='best3')count=3;
   else if(c.format==='cha-cha-cha')count=(i%3)+1;
   else if(c.format==='irish-fourball')count=i<6?1:i<12?2:i<17?3:ids.length;
   if(c.format==='yellow-ball'){
     const yellowId=ids[i%ids.length],yellow=available.find(x=>x.id===yellowId),others=available.filter(x=>x.id!==yellowId).sort((a,b)=>b.points-a.points);used=[...(yellow?[yellow]:[]),...(others.length?[others[0]]:[])];
   }else used=available.sort((a,b)=>b.points-a.points).slice(0,Math.min(count,available.length));
   const value=used.reduce((a,x)=>a+x.points,0);points+=value;holes.push({value,usedIds:used.map(x=>x.id),yellowId:c.format==='yellow-ball'?ids[i%ids.length]:null});
 }
 return {ids,complete:holes.filter(Boolean).length,points,rankValue:points,holes};
}
export function fourballMatchHandicaps(pairA,pairB,c,state){
 const all=[...(pairA?.ids||[]),...(pairB?.ids||[])].filter(Boolean);const course=state.courses.find(x=>x.id===c.course);const tee=course?.tees.find(t=>t.name===c.tee);const hs=tee?.holes||[];const par=hs.reduce((a,h)=>a+h.par,0)||72;const allowance=c.handicapAllowance??90;const ch=Object.fromEntries(all.map(id=>{const p=state.players.find(x=>x.id===id);return[id,rawCourseHandicap(p?.hi,tee,par)]}));if(!all.length)return{};const low=Math.min(...Object.values(ch));return Object.fromEntries(all.map(id=>[id,whsRound((ch[id]-low)*(allowance/100))]));
}
export function fourballMatchResult(pairA,pairB,c,state){
 const all=[...(pairA?.ids||[]),...(pairB?.ids||[])];const course=state.courses.find(x=>x.id===c.course);const tee=course?.tees.find(t=>t.name===c.tee);const hs=tee?.holes||[];const rel=fourballMatchHandicaps(pairA,pairB,c,state);const gross=id=>state.cards.find(x=>x.compId===c.id&&x.playerId===id)?.gross||[];let up=0,played=0,decided=false,decisionLeft=0;const holes=[];
 for(let i=0;i<hs.length;i++){const h=hs[i];const best=pair=>Math.min(...(pair.ids||[]).map(id=>{const g=+(gross(id)[i]||0);return g?g-holeStrokes(rel[id]||0,h.si):999}));const av=best(pairA),bv=best(pairB);if(av===999||bv===999){holes.push(null);continue}played++;if(av<bv)up++;else if(bv<av)up--;const remaining=hs.length-(i+1);holes.push({a:av,b:bv,up});if(Math.abs(up)>remaining){decided=true;decisionLeft=remaining;break}}
 const left=decided?decisionLeft:Math.max(0,hs.length-played);let text=up===0?'All Square':`${Math.abs(up)} UP`;if(decided)text=`${Math.abs(up)} & ${left}`;return{up,played,left,holes,relativeHandicaps:rel,text,decided};
}

