import{playingHandicap,scoreCard}from'./scoring.js';

export const WL_DEFAULTS={allowance:90,bestCount:8,cutStart:37,cutPerPoint:.5};

function compCourse(c,state){const course=state.courses.find(x=>x.id===c.course);const tee=course?.tees.find(t=>t.name===c.tee);const par=(tee?.holes||[]).reduce((a,h)=>a+(+h.par||0),0)||72;return{course,tee,par}}
export function wlCutForScore(score,settings=WL_DEFAULTS){const start=+(settings.cutStart??37),step=+(settings.cutPerPoint??.5);return score>=start?(score-start+1)*step:0}
function cardWithWLHandicap(card,player,c,state,teamCut,settings){const{tee,par}=compCourse(c,state);const base=playingHandicap(card?.handicapIndexUsed??player?.hi,tee,par,settings.allowance??90);return{...card,playingHandicap:base-teamCut,courseHandicap:card?.courseHandicap}}
function betterBall(ids,c,state,teamCut,settings){const results=ids.map(id=>{const player=state.players.find(p=>p.id===id);const card=state.cards.find(x=>x.compId===c.id&&x.playerId===id);if(!card)return null;return scoreCard(cardWithWLHandicap(card,player,c,state,teamCut,settings),{...c,format:'stableford',handicapAllowance:settings.allowance??90},state)}).filter(Boolean);if(!results.length)return null;const n=Math.max(...results.map(r=>r.holes.length));const holes=[];let points=0;for(let i=0;i<n;i++){const vals=results.map(r=>r.holes[i]).filter(h=>h?.gross>0).map(h=>h.points);const v=vals.length?Math.max(...vals):null;holes.push(v);if(v!=null)points+=v}return{points,holes,playersPlayed:results.length,complete:holes.filter(v=>v!=null).length,playerResults:results}}
function countbackKey(holes){const sum=n=>(holes||[]).slice(-n).reduce((a,v)=>a+(v||0),0);return[sum(9),sum(6),sum(3),sum(1)]}
function compareWeek(a,b){if(b.points!==a.points)return b.points-a.points;const ak=countbackKey(a.holes),bk=countbackKey(b.holes);for(let i=0;i<ak.length;i++)if(bk[i]!==ak[i])return bk[i]-ak[i];return 0}
export function winterLeagueTable(league,state){
 const settings={...WL_DEFAULTS,...(league.wlSettings||{})};const comps=(state.comps||[]).filter(c=>c.leagueId===league.id&&c.status!=='cancelled').sort((a,b)=>new Date(a.starts||0)-new Date(b.starts||0));const teams=(league.teams||[]).map(t=>({...t,weeks:[],teamCut:0}));
 const weekly=[];
 for(const c of comps){const rows=[];for(const t of teams){const r=betterBall(t.memberIds||[],c,state,t.teamCut,settings);const before=t.teamCut;if(r){const cut=wlCutForScore(r.points,settings);t.teamCut+=cut;const w={compId:c.id,name:c.name,date:c.starts,points:r.points,holes:r.holes,playersPlayed:r.playersPlayed,complete:r.complete,cut,beforeCut:before,afterCut:t.teamCut};t.weeks.push(w);rows.push({teamId:t.id,teamName:t.name,badgeImage:t.badgeImage||null,...w})}else t.weeks.push({compId:c.id,name:c.name,date:c.starts,points:null,holes:[],playersPlayed:0,complete:0,cut:0,beforeCut:before,afterCut:t.teamCut})}rows.sort(compareWeek);rows.forEach((r,i)=>r.position=i+1);weekly.push({comp:c,rows})}
 const bestCount=Math.min(+(settings.bestCount??8),comps.length);const table=teams.map(t=>{const scored=t.weeks.filter(w=>Number.isFinite(w.points));const counting=[...scored].sort((a,b)=>b.points-a.points).slice(0,bestCount);const total=counting.reduce((a,w)=>a+w.points,0);const countingIds=new Set(counting.map(w=>w.compId));return{...t,total,counting,countingIds,played:scored.length,finalCut:t.teamCut}});
 table.sort((a,b)=>{if(b.total!==a.total)return b.total-a.total;const ac=[...a.counting].sort((x,y)=>new Date(x.date||0)-new Date(y.date||0)),bc=[...b.counting].sort((x,y)=>new Date(x.date||0)-new Date(y.date||0));for(const n of [3,2,1]){const av=ac.slice(-n).reduce((s,w)=>s+w.points,0),bv=bc.slice(-n).reduce((s,w)=>s+w.points,0);if(bv!==av)return bv-av}return a.name.localeCompare(b.name)});table.forEach((r,i)=>r.position=i+1);
 return{settings,comps,weekly,table,bestCount}
}
